version: '3.8'

services:
  web:
    restart: always
    container_name: LJPS
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=spm
      - POSTGRES_DB=LJPS_DB

volumes:
  postgres_data: