# Generated by Django 4.1.1 on 2022-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LJPS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_role',
            name='Job_Role_Status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='Skill_Status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_Status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
