# Generated by Django 4.1.1 on 2022-10-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LJPS', '0003_alter_role_role_id_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Completion_Status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Reg_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Reg_Status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
