name: CI Pipeline

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Format with black
        run: |
          pip install black
          black .
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Sort imports
        run: |
          pip install isort
          isort .
          isort --check --diff .
      - name: Build image and start containers
        run: docker-compose up -d --build
      - name: Execute django tests in LJPS container
        run: docker exec LJPS python manage.py test
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down --volumes




